<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>cinemon-api-eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjNjFmMTc4YjZiNTBkODMwN2M3NzE1ZDQ4NjY4MmE5YSIsIm5iZiI6MTc4ODM3OTk4Ni40MTY5OTk4LCJzdWIiOiI2YTk4ODM1MjliYTA0ZDhlZGM4YmVlODUiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.VonYWfedbUj5quB4zb22HQL1xpGn1QCjVxwqFNPtgcc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.28" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.28">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cinemon.Application\Cinemon.Application.csproj" />
    <ProjectReference Include="..\Cinemon.Infrastructure\Cinemon.Infrastructure.csproj" />
  </ItemGroup>

</Project>
